### ISSUE TITLE
Why no field.get(pointer to instance) ?

### ISSUE THREAD

**Issue by exuvo** [jsoysouvanh/Refureku#11]
I am wondering why there are no public overloads of rfk::Field f.get(void*) (assume the field type is value) only references which require the actual class type to be known at compile time. It works just fine if i hackily cast my pointer to a dummy struct as you get the field value via getMemoryOffset anyway.

I know i can template my printField function but that will give me so many different template specifications and call sites one for each nested struct i support and i would need to manually write two lines per struct for the nested f.get(reference) to compile. Ie i need to test the type with rfk::getType and then get a struct reference with that type and the recurse my printFields function.

I tested a simpler approach which uses f.getConstPtr(instance) for the structs and then casts that pointer to a dummy struct reference
```
struct dummy { int ignored };
// In foreachField visitor:
const struct dummy& instance = *static_cast<const struct dummy*>(userData->pointer);
```
which works just fine and avoids me having to write a specific line for each kind of struct i may have (ie no need up update the printFields function if i add a new struct).

Is it really just the std::enable_if_t<is_value_v<OwnerStructType>>> check you use the type for?

Would it be possible to expose Field::getInternal(void const* instance) and Field::getConstPtrInternal(void const* instance) publicly with some warnings about unsafe usage?

**Comment by jsoysouvanh** [comment]
There are 2 different reasons I decided to switch the instance to a reference type (it was actually void* in 1.x.x if I remember well):
1. The user can't pass an invalid nullptr instance
2. Internally, the instance pointer can be adjusted (offseted) if necessary using the instance static type (this is actually not implemented yet but can cause bugs in some specific situations like the following one):
```cpp
class A
{
    int a;
    virtual ~A() = default;
};

class B
{
    int b;
    virtual ~B() = default;
};

class C : public A, public B {};

//....
C c;
rfk::Field const* aField = C::getStaticArchetype().getFieldByName("a"); //field a in class of type C

B& cAsB = c;
aField.get<int>(cAsB); //UB
```

In such a situation, the get method behaviour is undefined because offset is wrong (and the int is read from another memory address). Knowing the the static type of instance, we (dynamically) cast the reference from B& to C& and then retrieve the correct field with the above code (this is actually in my todo list).

However, I understand the necessity to be able to retrieve fields / execute methods from void* instances. Such unsafe situations should never happen when using single inheritance. I'll think about adding the unsafe methods both to rfk::Field and rfk::Method to be able to invoke methods / get-set fields from a void (const)* instance.

**Comment by exuvo** [comment]
Thanks that explains things. I have only single inheritance on my reflected objects so it should be safe.

**Comment by jsoysouvanh** [comment]
I added the Field::getUnsafe and the Field::setUnsafe methods that take a void* pointer on dev (commit ac170d5).
Tell me if it works for you, it will be incorporated in the next minor release.

**Comment by exuvo** [comment]
Wonderful i will test it tomorrow!

**Comment by exuvo** [comment]
I managed to get some free time and Yeah that is working perfectly!
