### ISSUE TITLE
Get field type name and comment

### ISSUE THREAD

**Issue by Flone-dnb** [jsoysouvanh/Refureku#13]
Hello! First of all I wanted to thank you for making this really helpful library!

After I integrated Refureku into my project I've started using `fieldType.match(rfk::getType<T>())` to deduce field types. I remember from the docs that comparing non-reflected types might not be correct and so I got into a situation where
```C++
rfk::getType<std::string>() == rfk::getType<std::vector<bool>>
````

I started thinking on how to get out of this situation and only come up with an idea to introduce a new property that will hint that the field is a vector not a string, but you could easily forget to mark your field with this property so I wanted to take this part under the hood. Can you help me out in this situation? Any ideas how to differentiate these types without changing field and its properties?

Because I have some experience with Unreal Engine, I remember that UE has a function to get C++ type name from a field (so for `std::vector<bool> someVector` field it should be a string that is equal to `std::vector<bool>`). I know nothing about how reflection systems work but because we can get field's name maybe we can also get C++ type from the field? This would solve my problem as I would have a way to differentiate types. Also, I know for sure that UE has a function to get C++ comment from a field (I use this functionality in one of the projects I'm working on), for example:
```C++
/** Key to jump. */
UPROPERTY()
FKey Jump;
```
will return "Key to jump." as a comment using reflection.
If you can add this (field type name and comment) to Refureku this would be super cool!

**Comment by jsoysouvanh** [comment]
Hello Flone, thank you for your feedback :)

rfk::Type::operator== will indeed return true for 2 unreflected types that have the exact same qualifiers, and std containers are not reflected by default, so you should reflect them to have the comparison work as expected. (note that for class templates, the template arguments types must be reflected too).

Now, your best bet to add reflection to std classes is to use a wrapper that is reflected, through composition or inheritance, as specified [on this wiki page](https://github.com/jsoysouvanh/Refureku/wiki/Struct-Class-template-manual-reflection). Your code should work correctly after that ;)

As for comments reflection, it is doable but I'm not sure I want to add the extra feature since it is already doable through custom properties like Unity "Tooltip" property, I believe UE also has a similar property that does the same. You have the tooltip example [on this wiki page](https://github.com/jsoysouvanh/Refureku/wiki/Create-custom-properties).

For the field type name, you can retrieve it with the rfk::Archetype::getName method. It is a bit more tedious for template types but you should be able to make a helper function in a few lines by iterating over the template arguments and retrieving their individual name, then concatenating them with the formatting you want.

Hope it helps!

**Comment by Flone-dnb** [comment]
Hey thanks for the quick answer!

I don't want to create wrappers around std classes because it's yet another thing for the API user to remember to do (which you can easily forget). And because archetypes are not available for non-reflected types it's pretty much impossible to solve my problem without creating custom classes. If we had a way to get field type name (as a string) for all types (even not reflected) that would solve my problem without introducing new complexities for the API user. But I totally understand if you don't want to add this feature. I might give it a try implementing myself in a fork (if I will be lucky enough to dig the code). :)

About field comments. Yes, I've seen the Tooltip property example and AFAIK UE has this in blueprints, but when they reflect a C++ function they show (in blueprint editor) a comment from C++ code (without any additional properties, because they have this feature implemented in their reflection system). I have not started integrating a scripting language to my project yet but here is what I foreshadow: you have a function in C++ with comments for documentation (Doxygen) and you reflect this function to a scripting language, now in order to have this function documentation available in your scripting language you have to copy-paste your function documentation to Tooltip property which is a not a good idea because you will have a duplicating text. Again, I haven't started integrating a scripting language but this is something I think I will stumble upon.

But once again. If you don't want to work on this or have concerns about those features, feel free to close this issue. I'm very happy with the current functionality as it's already a super helpful project. If I will have luck implementing something on my own I will notify you with a PR (if you will want to add this).

**Comment by jsoysouvanh** [comment]
If you take a look at the generated code on a very minimalist case, you might be able to manually write the generated code for the std classes you want to support like std::vector or std::string. I didn't mention this in the wiki since it's very tiresome but it's doable if the only thing you want is a valid rfk::Archetype.
Try to reflect an empty class template taking the same template params as std::vector and copy-paste de generated code ;)

For the scripting system bindings, I believe it may be preferable for you to generate the code with Kodgen instead of Refureku which is only here for **runtime** reflection purposes. It sounds more reasonable for me to add this feature in Kodgen to "bind" comments to C++ entities!

I'm really glad the library helps and I'm always open to new suggestions!

**Comment by Flone-dnb** [comment]
> you might be able to manually write the generated code

I usually try to avoid hacky approaches like this (which is also not a general solution either).

> Refureku which is only here for runtime reflection purposes

Didn't quite understand what you meant here (again, I have very little knowledge about reflection) but what I want is just being able to do this:
```C++
rfk::Field const& field = ...
field.getComment(); // returns const char* containing comment text
// and for other C++ entities like so
```
If you think you can implement this I will be super happy.

You can close this issue so it won't stay forever in "Open" state, I got enough information for my question. Thanks again!

**Comment by jsoysouvanh** [comment]
> I usually try to avoid hacky approaches like this (which is also not a general solution either).

That doesn't sound so much like a hacky approach to me. A lot of serialization libraries out there do not have a code generator and need manual registration through macros. The code generator for Refureku is just here for ease-of-use.
That being said, I just remembered this would not work for template classes like std::vector since the reflection of class templates relies on class code injection, that is not achievable on external libraries like std unfortunately.
For non-template classes, it is totally doable and not so tricky.

> Didn't quite understand what you meant here

I meant that instead of retrieving the comment from the runtime reflection system (i.e. Refureku), you can retrieve the comment from the code parser/generator (i.e. Kodgen) that will generate bindings code for your scripting language (just like it generates code for the reflection system). I think that's how UE4 works for blueprint bindings from C++ code (however I haven't checked it by myself so can't tell for sure).
Kodgen doesn't support the comments parsing yet but it sounds like a good and reasonable idea to implement the feature :)

I'm closing this issue for now, don't hesitate to hit me up if you have any other questions!
